---
abstract: 'Automatically sets repository URL from svn/svk/Git checkout for Dist::Zilla'
author:
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Ricardo SIGNES <rjbs@cpan.org>'
  - 'Moritz Onken <onken@netcubed.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Repository
recommends: {}
requires:
  Dist::Zilla: 1.007
resources:
  repository: http://github.com/fayland/dist-zilla-plugin-repository
version: 0.12
