---
abstract: 'Automatically sets repository URL from svn/svk/Git checkout for Dist::Zilla'
author:
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Ricardo SIGNES <rjbs@cpan.org>'
  - 'Moritz Onken <onken@netcubed.de>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092200'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Repository
requires:
  Dist::Zilla: 1.007
resources:
  repository: http://github.com/fayland/dist-zilla-plugin-repository/tree
version: 0.09
